fixed eror

diff --git a/bin/rpk b/bin/rpk
--- a/bin/rpk
+++ b/bin/rpk
@@ -394,8 +394,8 @@ command:major() {
 		local NEW="1.0.0"
 	fi
 
-	echo "$NEW\t$(git rev-parse HEAD)" | tee -a versions > /dev/null
-	git add versions && git commit -m "updated version to $NEW" versions || { popd > /dev/null; fatal "failed to commit version"; }
+	echo "$NEW\t$(git rev-parse HEAD)" | tee -a .$SELF/versions > /dev/null
+	git add .$SELF/versions && git commit -m "updated version to $NEW" .$SELF/versions || { popd > /dev/null; fatal "failed to commit version"; }
 	push:branches local || true
 	popd > /dev/null
 }
@@ -413,8 +413,8 @@ command:minor() {
 		local NEW="0.1.0"
 	fi
 		
-	echo "$NEW\t$(git rev-parse HEAD)" | tee -a versions > /dev/null
-	git add versions && git commit -m "updated version to $NEW" versions || { popd > /dev/null; fatal "failed to commit version"; }
+	echo "$NEW\t$(git rev-parse HEAD)" | tee -a .$SELF/versions > /dev/null
+	git add .$SELF/versions && git commit -m "updated version to $NEW" .$SELF/versions || { popd > /dev/null; fatal "failed to commit version"; }
 	push:branches local || true
 	popd > /dev/null
 }
