better error handling

diff --git a/bin/rpk b/bin/rpk
--- a/bin/rpk
+++ b/bin/rpk
@@ -698,7 +698,11 @@ EOF
 		chmod +x "$WORKTREE/.rpk/install"
 	fi
 
-	git add .rpk && git commit -m "initialized .rpk" || { popd > /dev/null; fatal "failed to commit .rpk files"; }
+	if git diff --cached --quiet; then
+		info "no changes to commit"
+	else
+		git add .rpk && git commit -m "initialized .rpk" || { popd > /dev/null; fatal "failed to commit .rpk files"; }
+	fi
 	push:branches local || true
 	popd > /dev/null
 }
